class Status:
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    DEAD = "DEAD"
    
class TaskTypes:
    SEND_MAIL = "SEND_MAIL"
    GENERATE_REPORT = "GENERATE_REPORT"
    PROCESS_IMAGE = "PROCESS IMAGE"
    PROCESS_FILE = "PROCESS_FILE"
    WEBHOOK_CALL  = "WEBHOOK_CALL"
    