class Status:
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    DEAD = "DEAD"
    
class TaskTypes:
    SEND_EMAIL = "SEND_MAIL"
    GENERATE_REPORT = "GENERATE_REPORT"
    PROCESS_IMAGE = "PROCESS_IMAGE"
    WEBHOOK_CALL  = "WEBHOOK_CALL"
